version: "3.8"
services:
  backend:
    build: ./API
    ports:
      - '8000:8000'
    volumes: 
      - logs:/app/logs
      - ./API:/app
      - /API/node_modules
  frontend:
    build: ./Front
    ports: 
      - '3000:3000'
    volumes: 
      - ./Front/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  data:
  logs:
